---
- name: Creates "deploy" directory
  file:
    path: /deploy
    state: directory

- name: Copying git key
  become: true
  copy:
    src: /home/esteban_dimier/.ssh/ed-git-key
    dest: /home/esteban_dimier/.ssh/
    owner: esteban_dimier
    group: esteban_dimier
    mode: 0644

- name: Copying compose file
  become: true
  copy:
    src: ./deploy/front/docker-compose.yml
    dest: /deploy/
    owner: esteban_dimier
    group: esteban_dimier
    mode: 0644

- name: Copying nginx conf file
  become: true
  copy:
    src: ./deploy/front/default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Clone a github repository (Seller)
  git:
    repo: git@github.com:MahjoPi/pimahtic-seller.git
    dest: /deploy/pimahtic-seller
    clone: yes
    update: yes
    key_file: /home/esteban_dimier/.ssh/ed-git-key
    accept_hostkey: yes

- name: Environment variables (Seller) ...

- name: Clone a github repository (Public)
  git:
    repo: git@github.com:MahjoPi/pimahtic-public.git
    dest: /deploy/pimahtic-public
    clone: yes
    update: yes
    key_file: /home/esteban_dimier/.ssh/ed-git-key
    accept_hostkey: yes

- name: Environment variables (Public) ...

- name: Clone a github repository (Backoffice)
  git:
    repo: git@github.com:MahjoPi/pimahtic-backoffice.git
    dest: /deploy/pimahtic-backoffice
    clone: yes
    update: yes
    key_file: /home/esteban_dimier/.ssh/ed-git-key
    accept_hostkey: yes

- name: Environment variables (Backoffice) ...

- name: Create and run containers
  shell: |
    cd /deploy
    sudo docker-compose up --no-start
    sudo docker-compose start