name: Deploy api on machine

on:
  push:
    branches:
      - preprod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          file: Dockerfile
          context: "{{defaultContext}}"
          push: false
          tags: europe-west1-docker.pkg.dev/environnement-de-test-329611/iac/api:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN }}
      - id: "auth"
        name: Authenticating to google cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_IAC_CREDENTIALS }}
      - name: authenticate to gcr
        uses: docker/login-action@v1
        with:
          registry: europe-west1-docker.pkg.dev # or REGION-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_IAC_CREDENTIALS }}
      - name: push to gcr
        run: |
          docker push europe-west1-docker.pkg.dev/environnement-de-test-329611/iac/api:latest

#  deploy:
#    runs-on: mahjopi-iac-back
#    steps:
#      - name: restarting the docker-compose
#        run: |
#          docker-compose down
#          docker-compose up -d
#        working-directory: /home/production/compose